import { buildParcours, type ParcoursNarrativeInput } from "@/lib/parcours-builders";

const ENTRIES: ParcoursNarrativeInput[] = [
  {
    slug: "sales-operations-manager",
    titre: "Sales Operations Manager",
    famille: "performance",
    cible: "Directeurs commerciaux, Sales Ops, Responsables croissance",
    promesse: "Piloter, automatiser et scaler ton activité commerciale avec l'IA.",
    prix: 1290,
    duree: "60h",
    niveau: "expert",
    equivalenceAcademique: "Bac+3 et au-delà",
    prerequis: [
      "Expérience commerciale ou management d'équipe",
      "Familiarité avec un CRM",
      "Appétence pour les données et le pilotage",
      "Curiosité pour l'automatisation",
    ],
    modules: [
      { code: "IA-01", titre: "Comprendre l'IA : ce que c'est, ce que ce n'est pas" },
      { code: "IA-02", titre: "Les outils IA du quotidien au travail" },
      { code: "IA-03", titre: "Écrire de bons prompts" },
      { code: "AUTO-01", titre: "Introduction à l'automatisation commerciale" },
      { code: "AUTO-02", titre: "Utiliser l'IA pour la prospection commerciale" },
      { code: "AUTO-03", titre: "Automatiser son CRM et son reporting commercial" },
      { code: "AUTO-04", titre: "Construire un workflow automatisé no-code" },
      { code: "AUTO-06", titre: "Piloter la performance commerciale avec l'IA" },
      { code: "PERF-01", titre: "Introduction au pilotage par les données" },
      { code: "PERF-02", titre: "Construire et suivre ses OKR" },
      { code: "PERF-04", titre: "Concevoir un tableau de bord stratégique" },
      { code: "NEGO-02", titre: "Préparer une négociation : BATNA" },
      { code: "NEGO-03", titre: "Assertivité : s'affirmer sans s'imposer" },
    ],
    addons: [
      {
        titre: "Analyse comportementale vente",
        prix: 120,
        benefit: "Décoder les signaux d'achat et adapter votre discours commercial.",
      },
      {
        titre: "Piloter une équipe par la performance",
        prix: 150,
        benefit: "Installer des rituels et des indicateurs pour engager vos équipes.",
      },
      {
        titre: "Communication stratégique",
        prix: 120,
        benefit: "Influencer les décisions avec des messages clairs et structurés.",
      },
    ],
    livrables: [
      "Dashboard de pilotage commercial complet — KPIs, OKR, alertes automatiques",
      "Workflow d'automatisation CRM opérationnel",
      "Stratégie de négociation documentée sur un cas complexe",
      "Tableau de bord de performance équipe",
    ],
    badge: "Sales Operations Manager Certifié Beyond",
    profils: [
      { titre: "Directeur commercial", desc: "Tu pilotes une équipe et tu veux des données fiables en temps réel." },
      { titre: "Sales Ops", desc: "Tu structures les process et tu veux automatiser ce qui peut l'être." },
      { titre: "Responsable croissance", desc: "Tu cherches à scaler sans recruter — l'IA comme levier." },
      { titre: "Manager confirmé", desc: "Tu as de l'expérience et tu veux passer à la dimension stratégique." },
    ],
    avantApres: {
      avant: [
        "Des reportings manuels qui prennent des heures",
        "Des process qui dépendent des personnes",
        "Des intuitions sans données pour décider",
        "Une prospection non scalable",
      ],
      apres: [
        "Un dashboard automatisé en temps réel",
        "Des workflows qui tournent sans toi",
        "Des décisions basées sur les données",
        "Une machine de prospection scalable",
      ],
    },
    faq: [
      {
        q: "Faut-il être développeur ?",
        r: "Non. Tout est no-code. L'objectif est d'être opérationnel sans compétence technique.",
      },
      {
        q: "Quel CRM est utilisé dans les exercices ?",
        r: "Les exercices sont adaptables à n'importe quel CRM — HubSpot, Salesforce, Pipedrive ou autre.",
      },
      {
        q: "Ce parcours remplace-t-il un recrutement ?",
        r: "Il te donne les compétences pour faire plus avec ton équipe actuelle avant de recruter.",
      },
    ],
  },
  {
    slug: "negociateur-sport",
    titre: "Négociateur Commercial Sport",
    famille: "performance",
    cible: "Commerciaux clubs sportifs, agences sport, structures événementielles",
    promesse: "Maîtriser la vente et la négociation dans l'écosystème sport professionnel.",
    prix: 990,
    duree: "55h",
    niveau: "praticien",
    equivalenceAcademique: "Bac+2 → Bac+3",
    prerequis: [
      "Intérêt pour le secteur sport",
      "Bases en relation commerciale",
      "Aucun prérequis technique",
      "Motivation à pratiquer sur des cas sport réels",
    ],
    modules: [
      { code: "SPORT-01", titre: "L'écosystème du sport professionnel" },
      { code: "SPORT-02", titre: "Construire et valoriser une offre partenariat sport" },
      { code: "SPORT-03", titre: "La négociation commerciale dans le sport" },
      { code: "SPORT-04", titre: "La vente en contexte événementiel sportif" },
      { code: "SPORT-05", titre: "Pilotage et développement commercial sport" },
      { code: "NEGO-01", titre: "Les bases de la négociation : positions vs intérêts" },
      { code: "NEGO-02", titre: "Préparer une négociation : BATNA" },
      { code: "NEGO-04", titre: "Négocier en situation de tension ou de conflit" },
      { code: "NEGO-05", titre: "Gérer les objections avec calme et précision" },
      { code: "COMPORT-03", titre: "Lire le comportement de ses interlocuteurs" },
      { code: "COMPORT-05", titre: "Analyse comportementale appliquée à la vente" },
      { code: "AUTO-02", titre: "Utiliser l'IA pour la prospection commerciale" },
      { code: "AUTO-03", titre: "Automatiser son CRM et son reporting" },
    ],
    addons: [
      {
        titre: "Comportement sous stress",
        prix: 120,
        benefit: "Rester efficace quand la pression monte en négociation.",
      },
      {
        titre: "Storytelling professionnel",
        prix: 100,
        benefit: "Raconter votre valeur et celle du partenariat avec impact.",
      },
      {
        titre: "Piloter la performance IA",
        prix: 120,
        benefit: "Mesurer et optimiser vos actions commerciales augmentées par l'IA.",
      },
    ],
    livrables: [
      "Offre partenariat sport complète — construite sur un cas concret",
      "Simulation de négociation avec un partenaire potentiel",
      "Pipeline CRM adapté au secteur sport",
      "Analyse comportementale de 3 profils d'interlocuteurs sport",
    ],
    badge: "Négociateur Commercial Sport Certifié Beyond",
    expert: {
      nom: "Jonathan Libert",
      titre: "Directeur Commercial",
      institution: "AS Nancy Lorraine",
      citation:
        "Dans le sport, la négociation ne ressemble à aucune autre. Les enjeux émotionnels, la pression médiatique, les délais — tout est différent. Ce parcours prépare à cette réalité.",
      image: "/images/expert-libert.jpg",
    },
    profils: [
      { titre: "Commercial club sportif", desc: "Tu vends des partenariats et tu veux structurer ta démarche." },
      { titre: "Agence sport", desc: "Tu négocies pour des marques et tu veux affiner ta posture." },
      { titre: "Reconversion sport", desc: "Tu veux entrer dans le secteur sport par la voie commerciale." },
      { titre: "Événementiel sportif", desc: "Tu vends des hospitality et des expériences premium." },
    ],
    avantApres: {
      avant: [
        "Des partenariats négociés à l'instinct sans méthode",
        "Une offre peu différenciée face aux concurrents",
        "Des tensions mal gérées avec sponsors ou médias",
        "Un pipeline sport peu structuré",
      ],
      apres: [
        "Une offre partenariat claire et valorisée",
        "Une posture de négociation calme et préparée",
        "Des accords durables alignés sur les intérêts",
        "Un CRM et un reporting adaptés au secteur sport",
      ],
    },
    faq: [
      {
        q: "Faut-il déjà travailler dans un club ?",
        r: "Non. Le parcours s'adresse aux commerciaux clubs, agences et événementiel — avec des cas concrets du sport pro.",
      },
      {
        q: "Le parcours couvre-t-il le sponsoring et l'hospitality ?",
        r: "Oui. Modules dédiés à l'offre partenariat, la vente événementielle et le pilotage commercial sport.",
      },
      {
        q: "L'IA est-elle vraiment utile dans le sport ?",
        r: "Pour la prospection, le reporting et la priorisation des comptes — oui, sans remplacer la relation humaine.",
      },
    ],
  },
  {
    slug: "manager-ia",
    titre: "Manager à l'ère de l'IA",
    famille: "leadership",
    cible: "Managers, directeurs, chefs de projet",
    promesse: "Manager autrement — avec l'IA comme outil et la cognition comme boussole.",
    prix: 990,
    duree: "50h",
    niveau: "praticien",
    equivalenceAcademique: "Bac+2 → Bac+3",
    prerequis: [
      "Une première expérience de management ou d'encadrement",
      "Curiosité pour l'IA et ses applications",
      "Volonté de faire évoluer ses pratiques",
      "Aucun prérequis technique",
    ],
    modules: [
      { code: "IA-01", titre: "Comprendre l'IA : ce que c'est, ce que ce n'est pas" },
      { code: "IA-03", titre: "Écrire de bons prompts" },
      { code: "IA-06", titre: "Éthique des algorithmes" },
      { code: "IA-07", titre: "Travailler avec l'IA en mode collaboratif" },
      { code: "AUTO-01", titre: "Introduction à l'automatisation" },
      { code: "AUTO-03", titre: "Automatiser son CRM et son reporting" },
      { code: "LEAD-02", titre: "Identifier et affirmer son style de leadership" },
      { code: "LEAD-03", titre: "Fixer des objectifs et déléguer efficacement" },
      { code: "LEAD-04", titre: "Manager des profils différents : management situationnel" },
      { code: "LEAD-05", titre: "Donner du sens : aligner équipe et mission" },
      { code: "COMPORT-06", titre: "Analyse comportementale appliquée au management" },
      { code: "PERF-04", titre: "Concevoir un tableau de bord stratégique" },
      { code: "META-03", titre: "Reconnaître ses biais cognitifs au quotidien" },
    ],
    addons: [
      {
        titre: "Conduire le changement",
        prix: 120,
        benefit: "Embarquer vos équipes dans les transformations sans les perdre.",
      },
      {
        titre: "Intelligence émotionnelle",
        prix: 150,
        benefit: "Réguler vos émotions et celles de vos collaborateurs au quotidien.",
      },
      {
        titre: "Communication de crise",
        prix: 120,
        benefit: "Communiquer avec transparence quand la situation se tend.",
      },
    ],
    livrables: [
      "Cartographie de son style de management et plan de développement",
      "Workflow d'automatisation de reporting opérationnel",
      "Plan de délégation structuré pour son équipe",
      "Analyse comportementale de 3 membres de son équipe",
    ],
    badge: "Manager à l'ère de l'IA Certifié Beyond",
    profils: [
      { titre: "Manager junior", desc: "Tu viens d'être promu et tu veux construire ta posture." },
      { titre: "Manager confirmé", desc: "Tu as de l'expérience et tu veux intégrer l'IA dans tes pratiques." },
      { titre: "Chef de projet", desc: "Tu coordonnes sans autorité hiérarchique — tu veux des outils." },
      { titre: "En transition", desc: "Tu changes de poste ou d'entreprise et tu veux te repositionner." },
    ],
    avantApres: {
      avant: [
        "Un management réactif sans vision partagée",
        "Des reportings chronophages pour l'équipe",
        "Des profils mal compris et des tensions récurrentes",
        "L'IA perçue comme une menace ou un gadget",
      ],
      apres: [
        "Une posture de leader claire et assumée",
        "Des automatisations qui libèrent du temps humain",
        "Une équipe alignée sur des objectifs explicites",
        "L'IA intégrée comme levier de performance collective",
      ],
    },
    faq: [
      {
        q: "Faut-il coder pour utiliser l'IA en management ?",
        r: "Non. Vous apprenez des usages concrets, prompts et workflows no-code adaptés au quotidien manager.",
      },
      {
        q: "Ce parcours convient-il aux chefs de projet sans équipe ?",
        r: "Oui. Délégation, influence et pilotage transversal sont au cœur du programme.",
      },
      {
        q: "Comment l'analyse comportementale aide-t-elle un manager ?",
        r: "À adapter votre communication, anticiper les tensions et mieux déléguer selon les profils.",
      },
    ],
  },
  {
    slug: "leader-transformation",
    titre: "Leader de la Transformation",
    famille: "leadership",
    cible: "Directeurs généraux, directeurs de BU, top managers",
    promesse: "Conduire la transformation de ton organisation avec clarté, sens et impact.",
    prix: 1290,
    duree: "60h",
    niveau: "expert",
    equivalenceAcademique: "Bac+3 et au-delà",
    prerequis: [
      "Expérience significative en management",
      "Responsabilité d'une équipe ou d'une BU",
      "Confronté à des enjeux de transformation",
      "Volonté d'évoluer dans sa posture de leader",
    ],
    modules: [
      { code: "LEAD-01", titre: "C'est quoi un leader ? Mythes et réalités" },
      { code: "LEAD-02", titre: "Identifier et affirmer son style de leadership" },
      { code: "LEAD-05", titre: "Donner du sens : aligner équipe et mission" },
      { code: "LEAD-06", titre: "Conduire le changement : embarquer les équipes" },
      { code: "LEAD-07", titre: "Leadership éthique et responsabilité sociétale" },
      { code: "IA-07", titre: "Travailler avec l'IA en mode collaboratif" },
      { code: "IA-08", titre: "Construire une stratégie de transformation IA" },
      { code: "AUTO-07", titre: "Déployer une stratégie d'automatisation à l'échelle" },
      { code: "COMPORT-07", titre: "Comportement sous stress et situations difficiles" },
      { code: "COMM-07", titre: "Communiquer en situation de crise" },
      { code: "COMM-08", titre: "Communication stratégique et influence organisationnelle" },
      { code: "PERF-06", titre: "Piloter la transformation par la performance" },
      { code: "RSE-05", titre: "Construire une stratégie de durabilité" },
    ],
    addons: [
      {
        titre: "Négociation multi-parties",
        prix: 150,
        benefit: "Aligner des intérêts divergents autour d'une décision commune.",
      },
      {
        titre: "Storytelling dirigeant",
        prix: 100,
        benefit: "Donner du sens et fédérer par le récit.",
      },
      {
        titre: "Prise de parole publique & médias",
        prix: 150,
        benefit: "Tenir le micro et l'antenne avec assurance.",
      },
    ],
    livrables: [
      "Feuille de route de transformation documentée sur 12 mois",
      "Plan de communication de crise opérationnel",
      "Stratégie IA pour son organisation",
      "Discours d'alignement équipe — construit et présenté",
    ],
    badge: "Leader de la Transformation Certifié Beyond",
    profils: [
      { titre: "Directeur général", desc: "Tu portes la vision et tu dois embarquer tout le CODIR." },
      { titre: "Directeur de BU", desc: "Tu transformes ton périmètre sans casser la performance." },
      { titre: "Top manager", desc: "Tu fais le lien entre stratégie groupe et terrain." },
      { titre: "DRH / DAF en mutation", desc: "Tu pilotes un chantier transversal à fort impact." },
    ],
    avantApres: {
      avant: [
        "Des transformations lancées sans adhésion des équipes",
        "Une stratégie IA floue ou déconnectée du métier",
        "Des crises mal anticipées et mal communiquées",
        "Un discours dirigeant peu mobilisateur",
      ],
      apres: [
        "Une feuille de route claire sur 12 mois",
        "Des équipes alignées autour d'un sens partagé",
        "Une stratégie IA et automatisation déployable",
        "Un plan de crise et une communication prêts à l'emploi",
      ],
    },
    faq: [
      {
        q: "Ce parcours est-il réservé aux DG ?",
        r: "Non. Il s'adresse à tout dirigeant ou top manager responsable d'une transformation d'envergure.",
      },
      {
        q: "La dimension RSE est-elle centrale ?",
        r: "Oui. Le leadership éthique et la durabilité sont intégrés au pilotage de la transformation.",
      },
      {
        q: "Faut-il une équipe projet dédiée ?",
        r: "Non. Vous apprenez à structurer la gouvernance et les rituels même avec des ressources limitées.",
      },
    ],
  },
  {
    slug: "entrepreneur-dirigeant",
    titre: "Entrepreneur & Dirigeant",
    famille: "leadership",
    cible: "Fondateurs, dirigeants et associés de PME en phase de croissance",
    promesse: "Scaler avec exigence — leadership, négociation et stratégie IA au service de la croissance.",
    prix: 1490,
    duree: "65h",
    niveau: "expert",
    equivalenceAcademique: "Bac+3 et au-delà",
    prerequis: [
      "Expérience de direction ou de création d'entreprise",
      "Responsabilité sur la stratégie et les arbitrages",
      "Ouverture à l'IA et à l'automatisation",
      "Volonté de structurer sa posture de dirigeant",
    ],
    modules: [
      { code: "LEAD-02", titre: "Identifier et affirmer son style de leadership" },
      { code: "LEAD-05", titre: "Donner du sens : aligner équipe et mission" },
      { code: "LEAD-07", titre: "Leadership éthique" },
      { code: "NEGO-06", titre: "Négociation complexe : multi-parties, enjeux élevés" },
      { code: "NEGO-07", titre: "Négociation stratégique et diplomatie organisationnelle" },
      { code: "COMM-06", titre: "Storytelling professionnel" },
      { code: "COMM-08", titre: "Communication stratégique et influence organisationnelle" },
      { code: "AUTO-06", titre: "Piloter la performance commerciale avec l'IA" },
      { code: "AUTO-07", titre: "Déployer une stratégie d'automatisation à l'échelle" },
      { code: "IA-07", titre: "Travailler avec l'IA en mode collaboratif" },
      { code: "IA-08", titre: "Construire une stratégie de transformation IA" },
      { code: "SOFT-05", titre: "Résilience : rebondir face à l'échec" },
      { code: "META-03", titre: "Reconnaître ses biais cognitifs" },
    ],
    addons: [
      {
        titre: "Pitch investisseurs",
        prix: 490,
        benefit: "Structurer et pitcher votre levée avec clarté et conviction.",
      },
      {
        titre: "Coaching dirigeant 3h",
        prix: 390,
        benefit: "Un accompagnement personnalisé sur vos enjeux stratégiques immédiats.",
      },
      {
        titre: "Gouvernance & pacte d'associés",
        prix: 290,
        benefit: "Sécuriser les relations entre associés et les décisions structurantes.",
      },
    ],
    livrables: [
      "Business plan opérationnel validé",
      "Pitch deck investisseurs ou partenaires",
      "Stratégie IA et automatisation pour la croissance",
      "Plan de communication dirigeant",
    ],
    badge: "Entrepreneur & Dirigeant Certifié Beyond",
    profils: [
      { titre: "Fondateur solo", desc: "Tu portes tout et tu veux structurer ta posture de dirigeant." },
      { titre: "Dirigeant PME", desc: "Tu scales une équipe et tu veux garder la maîtrise stratégique." },
      { titre: "Associé majoritaire", desc: "Tu négocies avec des partenaires, investisseurs ou board." },
      { titre: "Repreneur", desc: "Tu prends les rênes et tu veux accélérer sans te disperser." },
    ],
    avantApres: {
      avant: [
        "Une croissance portée par l'improvisation",
        "Des négociations sensibles mal préparées",
        "Un discours dirigeant peu structuré",
        "L'IA utilisée au cas par cas sans stratégie",
      ],
      apres: [
        "Une vision et un plan opérationnel partagés",
        "Des négociations complexes maîtrisées",
        "Une communication qui fédère équipes et partenaires",
        "Une feuille de route IA et automatisation alignée business",
      ],
    },
    faq: [
      {
        q: "Ce parcours remplace-t-il un MBA ?",
        r: "Non. Il est orienté terrain : leadership, négociation et IA appliqués à votre entreprise réelle.",
      },
      {
        q: "Convient-il à une TPE de moins de 10 personnes ?",
        r: "Oui, dès lors que vous portez la stratégie et voulez structurer votre croissance.",
      },
      {
        q: "Le pitch investisseurs est-il inclus ?",
        r: "Les fondamentaux sont dans le parcours ; l'add-on approfondit la préparation et le feedback.",
      },
    ],
  },
  {
    slug: "chief-of-staff",
    titre: "Chief of Staff",
    famille: "leadership",
    cible: "Bras droits de dirigeants, office managers stratégiques et PMO exécutifs",
    promesse: "Devenir le relais stratégique du dirigeant — priorisation, influence et exécution sans friction.",
    prix: 1090,
    duree: "55h",
    niveau: "expert",
    equivalenceAcademique: "Bac+3 et au-delà",
    prerequis: [
      "Expérience en coordination, cabinet ou direction générale",
      "Aisance relationnelle et discrétion",
      "Capacité à synthétiser et prioriser",
      "Curiosité pour l'IA et le pilotage",
    ],
    modules: [
      { code: "COMM-08", titre: "Communication stratégique et influence organisationnelle" },
      { code: "COMM-06", titre: "Storytelling professionnel" },
      { code: "LEAD-05", titre: "Donner du sens : aligner équipe et mission" },
      { code: "LEAD-06", titre: "Conduire le changement" },
      { code: "LEAD-03", titre: "Fixer des objectifs et déléguer efficacement" },
      { code: "PERF-04", titre: "Concevoir un tableau de bord stratégique" },
      { code: "PERF-02", titre: "Construire et suivre ses OKR" },
      { code: "IA-07", titre: "Travailler avec l'IA en mode collaboratif" },
      { code: "IA-03", titre: "Écrire de bons prompts" },
      { code: "NEGO-06", titre: "Négociation complexe : multi-parties" },
      { code: "NEGO-03", titre: "Assertivité" },
      { code: "COMPORT-03", titre: "Lire le comportement de ses interlocuteurs" },
    ],
    addons: [
      {
        titre: "Coaching exécutif 5h",
        prix: 390,
        benefit: "Affiner votre posture de bras droit avec un coach senior.",
      },
      {
        titre: "Atelier CODIR facilitation",
        prix: 290,
        benefit: "Préparer et animer des comités de direction efficaces.",
      },
      {
        titre: "Pack reporting dirigeant",
        prix: 250,
        benefit: "Automatiser les synthèses et tableaux de bord pour le COMEX.",
      },
    ],
    livrables: [
      "Système de pilotage CODIR opérationnel",
      "Tableau de bord stratégique et OKR documentés",
      "Kit de communication dirigeant",
      "Trame de facilitation pour comités exécutifs",
    ],
    badge: "Chief of Staff Certifié Beyond",
    profils: [
      { titre: "Chief of Staff", desc: "Tu veux structurer ton rôle de relais stratégique du CEO." },
      { titre: "Office manager senior", desc: "Tu passes du logistique à l'impact sur les décisions." },
      { titre: "PMO / chef de cabinet", desc: "Tu coordonnes des chantiers transverses à fort enjeu." },
      { titre: "DAF / DRH adjoint", desc: "Tu accompagnes le dirigeant sur des sujets sensibles." },
    ],
    avantApres: {
      avant: [
        "Des priorités floues et des arbitrages permanents",
        "Un CODIR peu préparé et des comités inefficaces",
        "Une communication dirigeant dispersée",
        "Des reportings manuels chronophages",
      ],
      apres: [
        "Une grille de priorisation claire et partagée",
        "Des rituels CODIR structurés et actionnables",
        "Des messages alignés et une influence maîtrisée",
        "Des tableaux de bord automatisés pour le dirigeant",
      ],
    },
    faq: [
      {
        q: "Faut-il déjà être Chief of Staff ?",
        r: "Non. Le parcours s'adresse à toute personne en relais direct d'un dirigeant ou en transition vers ce rôle.",
      },
      {
        q: "L'IA remplace-t-elle le travail de synthèse ?",
        r: "Non. Elle accélère la préparation ; votre jugement et votre relation au dirigeant restent centraux.",
      },
      {
        q: "Le parcours couvre-t-il la facilitation de comités ?",
        r: "Oui. OKR, tableaux de bord, communication stratégique et conduite du changement sont au programme.",
      },
    ],
  },
  {
    slug: "formateur-bct",
    titre: "Formateur Certifié Beyond (BCT)",
    famille: "humain",
    cible: "Formateurs, consultants pédagogiques et responsables formation",
    promesse: "Former en s'appuyant sur les sciences cognitives — pas seulement transmettre de l'information.",
    prix: 1490,
    duree: "70h",
    niveau: "praticien",
    equivalenceAcademique: "Bac+2 → Bac+3",
    prerequis: [
      "Expérience ou projet fort en formation / animation",
      "Volonté de structurer sa posture de formateur",
      "Aisance orale de base",
      "Aucun prérequis technique",
    ],
    modules: [
      { code: "META-01", titre: "Comment fonctionne mon cerveau quand j'apprends ?" },
      { code: "META-02", titre: "Apprendre à apprendre : stratégies et méthodes" },
      { code: "META-03", titre: "Reconnaître ses biais cognitifs au quotidien" },
      { code: "META-05", titre: "Pensée latérale et créativité structurée" },
      { code: "META-07", titre: "Développer une culture de l'apprentissage continu" },
      { code: "COMM-01", titre: "Les fondamentaux de la communication interpersonnelle" },
      { code: "COMM-05", titre: "Prise de parole en public : structure et présence" },
      { code: "COMM-06", titre: "Storytelling professionnel" },
      { code: "COMPORT-01", titre: "Fondements de l'analyse comportementale" },
      { code: "COMPORT-04", titre: "Adapter sa communication selon le profil" },
      { code: "LEAD-05", titre: "Donner du sens : aligner équipe et mission" },
      { code: "SOFT-04", titre: "Développer son empathie en contexte professionnel" },
      { code: "IA-03", titre: "Écrire de bons prompts" },
      { code: "IA-07", titre: "Travailler avec l'IA en mode collaboratif" },
    ],
    addons: [
      {
        titre: "Studio captation",
        prix: 290,
        benefit: "Produire des modules filmés professionnels pour vos formations.",
      },
      {
        titre: "Ingénierie pédagogique avancée",
        prix: 250,
        benefit: "Concevoir des parcours blended mesurables et certifiants.",
      },
      {
        titre: "Supervision formateur 4h",
        prix: 320,
        benefit: "Recevoir un feedback expert sur vos animations en conditions réelles.",
      },
    ],
    livrables: [
      "Parcours pédagogique complet documenté",
      "Session filmée ou animée en conditions réelles",
      "Kit d'animation et supports learners",
      "Certification Beyond Certified Trainer (BCT)",
    ],
    badge: "Beyond Certified Trainer (BCT)",
    expert: {
      nom: "Jessica Darcy",
      titre: "Psychopédagogue",
      institution: "Cabinet Neuroéducation",
      citation:
        "Former c'est comprendre comment le cerveau apprend — pas juste transmettre de l'information. Ce parcours donne les clés que la plupart des formateurs n'ont jamais reçues.",
      image: "/images/expert-jessica.jpg",
    },
    profils: [
      { titre: "Formateur indépendant", desc: "Tu veux professionnaliser ta pratique et te certifier." },
      { titre: "Consultant formation", desc: "Tu conçois des dispositifs pour tes clients." },
      { titre: "Responsable formation", desc: "Tu internalises l'expertise pédagogique dans ton entreprise." },
      { titre: "En reconversion", desc: "Tu veux devenir formateur avec une méthode reconnue." },
    ],
    avantApres: {
      avant: [
        "Des formations centrées sur le contenu, peu sur l'apprenant",
        "Une animation qui fatigue sans ancrer les acquis",
        "Des supports peu engageants",
        "L'IA utilisée sans cadre pédagogique",
      ],
      apres: [
        "Des parcours alignés sur le fonctionnement du cerveau",
        "Une posture de formateur structurée et certifiée",
        "Des sessions filmées ou animées avec impact",
        "L'IA intégrée comme co-pilote pédagogique",
      ],
    },
    faq: [
      {
        q: "La certification BCT est-elle reconnue ?",
        r: "C'est la certification interne Beyond, complétée par un Open Badge et un portfolio de sessions.",
      },
      {
        q: "Faut-il déjà animer régulièrement ?",
        r: "Une première expérience ou un projet concret suffit — le parcours est très pratique.",
      },
      {
        q: "Le studio captation est-il obligatoire ?",
        r: "Non. C'est un add-on pour ceux qui veulent produire du contenu filmé professionnel.",
      },
    ],
  },
  {
    slug: "hr-business-partner",
    titre: "HR Business Partner",
    famille: "humain",
    cible: "RH généralistes, HRBP et responsables people en lien avec le métier",
    promesse: "Devenir un vrai partenaire business — recrutement, talents et changement alignés sur la performance.",
    prix: 1290,
    duree: "65h",
    niveau: "praticien",
    equivalenceAcademique: "Bac+2 → Bac+3",
    prerequis: [
      "Expérience en RH ou en accompagnement des managers",
      "Intérêt pour le lien métier / people",
      "Aisance relationnelle",
      "Aucun prérequis technique",
    ],
    modules: [
      { code: "COMPORT-01", titre: "Fondements de l'analyse comportementale" },
      { code: "COMPORT-02", titre: "Se connaître : identifier son profil comportemental" },
      { code: "COMPORT-03", titre: "Lire le comportement de ses interlocuteurs" },
      { code: "COMPORT-06", titre: "Analyse comportementale appliquée au management" },
      { code: "SOFT-01", titre: "Comprendre ses émotions : le vocabulaire émotionnel" },
      { code: "SOFT-04", titre: "Développer son empathie en contexte professionnel" },
      { code: "LEAD-04", titre: "Manager des profils différents : management situationnel" },
      { code: "LEAD-06", titre: "Conduire le changement : embarquer les équipes" },
      { code: "RH-01", titre: "Les fondamentaux du recrutement efficace" },
      { code: "RH-02", titre: "Conduire un entretien de recrutement structuré" },
      { code: "RH-03", titre: "Construire et rayonner sa marque employeur" },
      { code: "RH-04", titre: "Onboarding : intégrer et fidéliser les nouveaux talents" },
      { code: "META-07", titre: "Développer une culture de l'apprentissage continu" },
    ],
    addons: [
      {
        titre: "Campagne talent review",
        prix: 350,
        benefit: "Structurer une revue des talents alignée sur les enjeux métier.",
      },
      {
        titre: "Assessment center",
        prix: 290,
        benefit: "Concevoir et piloter des assessments pour vos populations clés.",
      },
      {
        titre: "Politique mobilité interne",
        prix: 250,
        benefit: "Déployer une grille de mobilité et de développement des carrières.",
      },
    ],
    livrables: [
      "Grille compétences métier validée",
      "Process de recrutement et entretien structuré",
      "Plan mobilité interne et marque employeur",
      "Kit conduite du changement RH",
    ],
    badge: "HR Business Partner Certifié Beyond",
    profils: [
      { titre: "RH généraliste", desc: "Tu veux te positionner en partenaire des métiers." },
      { titre: "HRBP confirmé", desc: "Tu affines tes leviers recrutement, talents et changement." },
      { titre: "Responsable people PME", desc: "Tu structures les RH avec peu de ressources." },
      { titre: "Consultant RH", desc: "Tu veux une méthode certifiante pour tes clients." },
    ],
    avantApres: {
      avant: [
        "Des RH perçues comme administratives",
        "Des recrutements longs et peu alignés métier",
        "Une marque employeur peu différenciante",
        "Des managers peu outillés sur les profils",
      ],
      apres: [
        "Un rôle de partenaire business reconnu",
        "Des process de recrutement et onboarding efficaces",
        "Une stratégie talents et mobilité documentée",
        "Des managers accompagnés sur le comportemental",
      ],
    },
    faq: [
      {
        q: "Ce parcours est-il adapté sans expérience RH longue ?",
        r: "Une première expérience RH ou un rôle people en PME suffit si vous êtes en lien avec les managers.",
      },
      {
        q: "La marque employeur est-elle au programme ?",
        r: "Oui. Module dédié et livrable sur votre stratégie employeur.",
      },
      {
        q: "L'analyse comportementale est-elle certifiante ?",
        r: "Vous maîtrisez les fondamentaux Beyond appliqués au recrutement et au management situationnel.",
      },
    ],
  },
  {
    slug: "coach-facilitateur",
    titre: "Coach & Facilitateur Professionnel",
    famille: "humain",
    cible: "Coachs, facilitateurs et consultants en développement humain",
    promesse: "Installer une posture coach et faciliter des groupes avec méthode, éthique et impact.",
    prix: 1290,
    duree: "60h",
    niveau: "praticien",
    equivalenceAcademique: "Bac+2 → Bac+3",
    prerequis: [
      "Expérience d'accompagnement ou d'animation de groupes",
      "Écoute et confidentialité",
      "Volonté de structurer sa pratique",
      "Aucun prérequis technique",
    ],
    modules: [
      { code: "SOFT-01", titre: "Comprendre ses émotions" },
      { code: "SOFT-02", titre: "Réguler ses émotions sous pression" },
      { code: "SOFT-04", titre: "Développer son empathie" },
      { code: "SOFT-05", titre: "Résilience : rebondir face à l'échec" },
      { code: "SOFT-06", titre: "Exercer son jugement moral" },
      { code: "COMM-01", titre: "Les fondamentaux de la communication interpersonnelle" },
      { code: "COMM-02", titre: "Écouter vraiment : l'écoute active" },
      { code: "COMM-04", titre: "CNV : bases" },
      { code: "COMM-05", titre: "Prise de parole en public" },
      { code: "META-05", titre: "Pensée latérale et créativité structurée" },
      { code: "META-06", titre: "Raisonnement en situation d'ambiguïté" },
      { code: "COMPORT-01", titre: "Fondements de l'analyse comportementale" },
    ],
    addons: [
      {
        titre: "Supervision 6 séances",
        prix: 390,
        benefit: "Consolider votre posture avec un superviseur expérimenté.",
      },
      {
        titre: "Facilitation design thinking",
        prix: 290,
        benefit: "Animer des ateliers d'innovation et de co-création en entreprise.",
      },
      {
        titre: "Portfolio certification",
        prix: 190,
        benefit: "Structurer vos preuves de pratique pour la certification Beyond.",
      },
    ],
    livrables: [
      "Portfolio de séances documentées",
      "Certification facilitation et coaching Beyond",
      "Grille d'éthique et de cadrage des séances",
      "Trames d'animation pour ateliers collectifs",
    ],
    badge: "Coach & Facilitateur Certifié Beyond",
    profils: [
      { titre: "Coach professionnel", desc: "Tu veux structurer ta pratique et te certifier." },
      { titre: "Facilitateur", desc: "Tu animes des groupes et tu veux des méthodes éprouvées." },
      { titre: "Consultant RH", desc: "Tu ajoutes le coaching à ton offre d'accompagnement." },
      { titre: "Manager coach", desc: "Tu accompagnes ton équipe avec une posture coach." },
    ],
    avantApres: {
      avant: [
        "Une pratique intuitive sans cadre éthique clair",
        "Des séances qui manquent de structure",
        "Des ateliers collectifs peu engageants",
        "Des émotions difficiles à tenir en séance",
      ],
      apres: [
        "Une posture coach assumée et certifiée",
        "Des trames de séance et de facilitation opérationnelles",
        "Une écoute active et une CNV maîtrisées",
        "Un portfolio de pratiques validé",
      ],
    },
    faq: [
      {
        q: "Ce parcours remplace une certification ICF ?",
        r: "Non. C'est la certification Beyond orientée posture, facilitation et outils comportementaux.",
      },
      {
        q: "La supervision est-elle obligatoire ?",
        r: "Recommandée pour les coachs en exercice ; disponible en add-on approfondi.",
      },
      {
        q: "Puis-je faciliter sans être coach ?",
        r: "Oui. Le parcours couvre facilitation collective et coaching individuel.",
      },
    ],
  },
  {
    slug: "developpeur-talents",
    titre: "Développeur de Talents",
    famille: "humain",
    cible: "Responsables talents, L&D et chargés de développement des compétences",
    promesse: "Construire des parcours de talents durables — du recrutement à la mobilité interne.",
    prix: 1090,
    duree: "55h",
    niveau: "praticien",
    equivalenceAcademique: "Bac+2 → Bac+3",
    prerequis: [
      "Expérience en formation, RH ou management",
      "Intérêt pour le développement des compétences",
      "Capacité à piloter des projets transverses",
      "Aucun prérequis technique",
    ],
    modules: [
      { code: "META-01", titre: "Comment fonctionne mon cerveau quand j'apprends ?" },
      { code: "META-02", titre: "Apprendre à apprendre" },
      { code: "META-07", titre: "Développer une culture de l'apprentissage continu" },
      { code: "RH-01", titre: "Les fondamentaux du recrutement efficace" },
      { code: "RH-02", titre: "Conduire un entretien de recrutement structuré" },
      { code: "RH-04", titre: "Onboarding : intégrer et fidéliser les nouveaux talents" },
      { code: "RH-05", titre: "Stratégie d'attraction et de rétention des talents" },
      { code: "COMPORT-06", titre: "Analyse comportementale appliquée au management" },
      { code: "LEAD-04", titre: "Manager des profils différents" },
      { code: "LEAD-05", titre: "Donner du sens" },
      { code: "SOFT-04", titre: "Développer son empathie" },
      { code: "SOFT-05", titre: "Résilience : rebondir face à l'échec" },
    ],
    addons: [
      {
        titre: "Campagne assessment",
        prix: 290,
        benefit: "Identifier les potentiels et gaps de compétences à l'échelle.",
      },
      {
        titre: "Plan de mobilité interne",
        prix: 250,
        benefit: "Cartographier les parcours de carrière et les mobilités possibles.",
      },
      {
        titre: "Université interne",
        prix: 320,
        benefit: "Structurer un catalogue de formations aligné sur les métiers.",
      },
    ],
    livrables: [
      "Matrice talents et compétences",
      "Plan de développement et rétention",
      "Process onboarding et entretiens structurés",
      "Culture d'apprentissage continu documentée",
    ],
    badge: "Développeur de Talents Certifié Beyond",
    profils: [
      { titre: "Responsable L&D", desc: "Tu construis les parcours de formation et de montée en compétences." },
      { titre: "Talent manager", desc: "Tu pilotes attraction, rétention et mobilité." },
      { titre: "RH développement", desc: "Tu alignes people et stratégie métier." },
      { titre: "Manager formateur", desc: "Tu développes les talents de ton équipe au quotidien." },
    ],
    avantApres: {
      avant: [
        "Des plans de formation déconnectés des métiers",
        "Une rétention des talents fragile",
        "Un onboarding peu structuré",
        "Peu de visibilité sur les compétences clés",
      ],
      apres: [
        "Une matrice talents opérationnelle",
        "Des parcours de mobilité et développement clairs",
        "Un onboarding qui fidélise dès les 90 premiers jours",
        "Une culture d'apprentissage ancrée",
      ],
    },
    faq: [
      {
        q: "Ce parcours est-il réservé aux grandes entreprises ?",
        r: "Non. Les outils sont adaptables aux PME avec peu de ressources RH.",
      },
      {
        q: "Le recrutement est-il inclus ?",
        r: "Oui. Fondamentaux, entretien structuré et lien avec la stratégie talents.",
      },
      {
        q: "Quelle différence avec HR Business Partner ?",
        r: "Développeur de Talents est centré L&D, mobilité et montée en compétences ; HRBP sur le partenariat métier global.",
      },
    ],
  },
  {
    slug: "product-builder",
    titre: "Product Builder",
    famille: "innovation",
    cible: "Fondateurs, consultants, entrepreneurs, experts qui veulent productiser",
    promesse: "De l'idée au MVP en ligne — sans coder une ligne.",
    prix: 1190,
    duree: "50h",
    niveau: "fondateur",
    equivalenceAcademique: "Accessible à tous — aucun prérequis",
    prerequis: [
      "Aucun prérequis technique — zéro code",
      "Une idée de produit ou un problème à résoudre",
      "Capacité à consacrer 4 à 6h par semaine",
      "Curiosité pour l'IA et les outils no-code",
    ],
    modules: [
      { code: "PROD-01", titre: "Penser produit : du problème à l'idée viable" },
      { code: "PROD-02", titre: "Connaître ses utilisateurs : recherche et empathie" },
      { code: "PROD-03", titre: "Designer son produit sans coder : UX & maquettage" },
      { code: "PROD-04", titre: "Construire son MVP no-code" },
      { code: "PROD-05", titre: "L'IA comme co-pilote du builder" },
      { code: "PROD-06", titre: "Valider son marché avant d'investir" },
      { code: "PROD-07", titre: "Monétiser son produit : modèles et pricing" },
      { code: "PROD-08", titre: "Acquérir ses premiers utilisateurs sans budget" },
      { code: "PROD-09", titre: "Itérer vite : feedback, données, décisions" },
      { code: "PROD-10", titre: "De l'MVP au produit qui scale" },
    ],
    addons: [
      {
        titre: "Storytelling & pitch investisseur",
        prix: 150,
        benefit: "Convaincre investisseurs et partenaires en quelques minutes.",
      },
      {
        titre: "Automatisation commerciale pour builders",
        prix: 120,
        benefit: "Scaler l'acquisition sans recruter une armée commerciale.",
      },
      {
        titre: "Négociation avec partenaires et prestataires",
        prix: 120,
        benefit: "Sécuriser vos deals sans sacrifier vos marges.",
      },
    ],
    livrables: [
      "MVP fonctionnel en ligne — accessible via URL publique",
      "Landing page de validation avec métriques réelles",
      "Stratégie de monétisation documentée avec page pricing",
      "Plan de lancement 30 jours avec rapport post-lancement",
    ],
    badge: "Product Builder Certifié Beyond",
    profils: [
      { titre: "Fondateur", desc: "Tu as une idée et tu veux la tester sans dépenser 50K en dev." },
      { titre: "Consultant", desc: "Tu veux productiser ton expertise sous forme de SaaS ou d'outil." },
      { titre: "Salarié", desc: "Tu veux lancer un side project sans quitter ton emploi." },
      { titre: "Expert métier", desc: "Tu veux créer un produit autour de ce que tu sais faire." },
    ],
    avantApres: {
      avant: [
        "Une idée non validée et des hypothèses floues",
        "Une dépendance aux développeurs ou agences",
        "Aucun MVP accessible en ligne",
        "Un go-to-market improvisé",
      ],
      apres: [
        "Un problème utilisateur validé",
        "Un MVP no-code en production",
        "Une stratégie pricing et acquisition documentée",
        "Un plan de lancement 30 jours exécuté",
      ],
    },
    faq: [
      {
        q: "Faut-il savoir coder ?",
        r: "Non. Zéro code — no-code et IA comme stack principale.",
      },
      {
        q: "Puis-je partir sans idée de produit ?",
        r: "Mieux vaut un problème ou une expertise à explorer ; le parcours structure la discovery.",
      },
      {
        q: "Le MVP est-il vraiment en ligne ?",
        r: "Oui. Livrable attendu : URL publique et métriques de validation.",
      },
    ],
  },
  {
    slug: "intrapreneur-innovation",
    titre: "Intrapreneur & Innovation Manager",
    famille: "innovation",
    cible: "Intrapreneurs, responsables innovation et chefs de projet transformation",
    promesse: "Lancer et piloter des initiatives innovantes en entreprise — de l'idée au déploiement.",
    prix: 990,
    duree: "50h",
    niveau: "praticien",
    equivalenceAcademique: "Bac+2 → Bac+3",
    prerequis: [
      "Expérience en entreprise ou en conduite de projet",
      "Mandat ou sponsor pour une initiative innovante",
      "Ouverture à l'IA et au no-code",
      "Capacité à embarquer des parties prenantes",
    ],
    modules: [
      { code: "META-05", titre: "Pensée latérale et créativité structurée" },
      { code: "META-06", titre: "Raisonnement en situation d'ambiguïté" },
      { code: "META-03", titre: "Reconnaître ses biais cognitifs" },
      { code: "IA-07", titre: "Travailler avec l'IA en mode collaboratif" },
      { code: "IA-08", titre: "Construire une stratégie de transformation IA" },
      { code: "AUTO-04", titre: "Construire un workflow automatisé no-code" },
      { code: "LEAD-06", titre: "Conduire le changement" },
      { code: "LEAD-05", titre: "Donner du sens" },
      { code: "COMM-06", titre: "Storytelling professionnel" },
      { code: "COMM-08", titre: "Communication stratégique" },
      { code: "PERF-06", titre: "Piloter la transformation par la performance" },
    ],
    addons: [
      {
        titre: "Design sprint 2j",
        prix: 390,
        benefit: "Accélérer la validation d'une innovation avec un format intensif.",
      },
      {
        titre: "Business case investisseurs internes",
        prix: 290,
        benefit: "Construire un dossier convaincant pour votre comité d'investissement.",
      },
      {
        titre: "Portfolio intrapreneuriat",
        prix: 250,
        benefit: "Structurer et prioriser plusieurs initiatives en parallèle.",
      },
    ],
    livrables: [
      "Business case innovation validé",
      "Prototype ou workflow no-code opérationnel",
      "Plan de conduite du changement",
      "Pitch storytelling pour sponsors internes",
    ],
    badge: "Intrapreneur & Innovation Manager Certifié Beyond",
    profils: [
      { titre: "Intrapreneur", desc: "Tu portes une initiative nouvelle dans ton entreprise." },
      { titre: "Responsable innovation", desc: "Tu structures un portefeuille de projets." },
      { titre: "Chef de projet transformation", desc: "Tu fais le lien entre stratégie et terrain." },
      { titre: "Manager explorateur", desc: "Tu testes de nouveaux modèles dans ton périmètre." },
    ],
    avantApres: {
      avant: [
        "Des idées qui peinent à obtenir un budget",
        "Des projets innovation isolés du métier",
        "Une conduite du changement improvisée",
        "Peu d'outils pour prototyper vite",
      ],
      apres: [
        "Un business case structuré et défendable",
        "Un prototype ou workflow validé en conditions réelles",
        "Des parties prenantes embarquées",
        "Une communication qui donne du sens au projet",
      ],
    },
    faq: [
      {
        q: "Faut-il un budget innovation dédié ?",
        r: "Non. Le parcours aide à construire le dossier et à obtenir un sponsor interne.",
      },
      {
        q: "Le no-code est-il au programme ?",
        r: "Oui. Workflow automatisé et prototypage rapide sans équipe technique.",
      },
      {
        q: "Différence avec Product Builder ?",
        r: "Intrapreneur est centré entreprise, sponsors et changement ; Product Builder sur le MVP marché.",
      },
    ],
  },
  {
    slug: "rse-sustainability",
    titre: "RSE & Sustainability Officer",
    famille: "innovation",
    cible: "Responsables RSE, QHSE et managers engagés sur la durabilité",
    promesse: "Piloter une démarche RSE crédible — du diagnostic à la stratégie et à l'influence interne.",
    prix: 890,
    duree: "45h",
    niveau: "fondateur",
    equivalenceAcademique: "Accessible à tous",
    prerequis: [
      "Intérêt pour les enjeux climat et responsabilité",
      "Rôle ou projet RSE en entreprise (ou volonté d'en créer un)",
      "Capacité à embarquer des équipes",
      "Aucun prérequis technique",
    ],
    modules: [
      { code: "RSE-01", titre: "Comprendre les enjeux climatiques en entreprise" },
      { code: "RSE-02", titre: "Les bases de la RSE" },
      { code: "RSE-03", titre: "Intégrer l'éco-conception dans ses projets" },
      { code: "RSE-04", titre: "Piloter une démarche RSE dans son équipe" },
      { code: "RSE-05", titre: "Construire une stratégie de durabilité" },
      { code: "COMM-08", titre: "Communication stratégique et influence organisationnelle" },
      { code: "LEAD-06", titre: "Conduire le changement" },
      { code: "LEAD-07", titre: "Leadership éthique" },
      { code: "PERF-06", titre: "Piloter la transformation par la performance" },
      { code: "PERF-04", titre: "Concevoir un tableau de bord stratégique" },
      { code: "SOFT-06", titre: "Exercer son jugement moral" },
    ],
    addons: [
      {
        titre: "Bilan carbone simplifié",
        prix: 290,
        benefit: "Réaliser un premier diagnostic émissions actionnable.",
      },
      {
        titre: "Reporting CSRD / DPEF",
        prix: 350,
        benefit: "Structurer vos indicateurs pour les exigences réglementaires.",
      },
      {
        titre: "Atelier parties prenantes",
        prix: 250,
        benefit: "Mobiliser internes et externes autour de votre feuille de route RSE.",
      },
    ],
    livrables: [
      "Diagnostic RSE et feuille de route 12 mois",
      "Tableau de bord durabilité",
      "Plan de communication et conduite du changement",
      "Stratégie éco-conception sur un projet pilote",
    ],
    badge: "RSE & Sustainability Officer Certifié Beyond",
    profils: [
      { titre: "Responsable RSE", desc: "Tu structures ou renforces la démarche dans ton organisation." },
      { titre: "Manager engagé", desc: "Tu portes la durabilité dans ton équipe ou ta BU." },
      { titre: "QHSE en mutation", desc: "Tu élargis ton périmètre vers la responsabilité sociétale." },
      { titre: "Consultant durabilité", desc: "Tu veux une méthode certifiante pour tes clients." },
    ],
    avantApres: {
      avant: [
        "Une RSE perçue comme greenwashing",
        "Des actions dispersées sans indicateurs",
        "Peu d'adhésion des équipes",
        "Un discours peu crédible en interne",
      ],
      apres: [
        "Une stratégie de durabilité documentée",
        "Un tableau de bord avec indicateurs clés",
        "Des équipes embarquées dans le changement",
        "Une communication stratégique alignée",
      ],
    },
    faq: [
      {
        q: "Faut-il être expert climat ?",
        r: "Non. Le parcours donne les fondamentaux et les outils de pilotage accessibles.",
      },
      {
        q: "La CSRD est-elle couverte ?",
        r: "Les bases de reporting sont abordées ; l'add-on approfondit selon votre contexte.",
      },
      {
        q: "Convient-il aux PME ?",
        r: "Oui. La démarche est scalable, y compris sans équipe RSE dédiée.",
      },
    ],
  },
];

export const PARCOURS_EXTENDED = ENTRIES.map(buildParcours);
