export type ReferentialItem = string | { name: string; subtitle: string };

export function referentialItemName(item: ReferentialItem): string {
  return typeof item === "string" ? item : item.name;
}

export function referentialItemSubtitle(item: ReferentialItem): string | undefined {
  return typeof item === "string" ? undefined : item.subtitle;
}

export const GLOBAL_STACK_REFERENTIAL = [
  {
    category: "Frontend",
    items: [
      "React.js",
      "Next.js (App Router)",
      "Tailwind CSS",
      "TypeScript",
      "Framer Motion",
      "Web Accessibility (a11y)",
    ],
  },
  {
    category: "Backend & Cloud",
    items: [
      "Node.js",
      "Python (FastAPI)",
      "Serverless Functions",
      "Edge Computing",
      "Docker",
      "Kubernetes",
    ],
  },
  {
    category: "Data & IA",
    items: [
      "PostgreSQL",
      "Supabase",
      "Redis",
      "Pinecone",
      "Chroma",
      "OpenAI API",
      "Anthropic API",
      "LangChain",
      "Vercel AI SDK",
      "RAG",
      "Fine-tuning",
    ],
  },
  {
    category: "Automation & Ops",
    items: ["n8n", "Make", "Zapier", "Phantombuster", "HubSpot", "Salesforce", "Linear", "Notion", "Hotjar"],
  },
  {
    category: "No-code / CMS",
    items: ["WordPress", "Webflow", "Shopify", "WooCommerce", "Magento", "Joomla", "Bubble", "FlutterFlow"],
  },
  {
    category: "Design & Product",
    items: ["Figma", "Design Systems", "UX Research", "Prototypage", "Méthode Agile/Scrum", "Roadmap Produit"],
  },
] as const;

export const GLOBAL_SKILL_REFERENTIAL: Array<{ category: string; items: ReferentialItem[] }> = [
  {
    category: "Vente & Négociation",
    items: [
      { name: "Empathie Tactique", subtitle: "Comprendre les motivations cachées de l'interlocuteur" },
      { name: "Étiquetage Émotionnel (Labeling)", subtitle: "Nommer l'émotion ressentie pour apaiser la tension" },
      { name: "Miroir (Mirroring)", subtitle: "Reprendre les mots de l'interlocuteur pour créer du lien" },
      { name: "Questions Calibrées", subtitle: "Poser des questions ouvertes qui invitent à réfléchir" },
      "Ancrage de Prix",
      "Gestion du Silence",
      "Détection du Mensonge",
      "Analyse des types de personnalités (DISC)",
      "Biais Cognitifs",
      "Preuve Sociale",
      "Réciprocité",
      { name: "Gestion de l'Urgence (FOMO)", subtitle: "Créer un sentiment d'urgence sans manipulation" },
      "Vente de Valeur (Value-Based)",
      { name: "SPIN Selling", subtitle: "Questionnement Situation → Problème → Implication → Besoin" },
      {
        name: "Traitement des objections complexes (PANT)",
        subtitle: "Problème, Amplification, Nécessité, Transfert de solution",
      },
      { name: "Closing Assomptif", subtitle: "Conclure en partant du principe que l'accord est acquis" },
      "Négociation de Contrat (Legal/Procurement)",
      "Gestion du Cycle de Vente Long",
    ],
  },
  {
    category: "Business Development & Prospection",
    items: [
      { name: "Account-Based Marketing (ABM)", subtitle: "Cibler des comptes clés avec une approche sur mesure" },
      "Cold Calling",
      "Cold Emailing (Délivrabilité)",
      "Social Selling (LinkedIn)",
      {
        name: "Multi-Channel Sequencing",
        subtitle: "Enchaîner mail, téléphone et LinkedIn dans une même prospection",
      },
      "Vente Émotionnelle",
      "Scripts de Vente Directe",
      "Closing Téléphonique",
      "Gestion de Volume de Leads",
      { name: "Lead Scoring", subtitle: "Classer les prospects selon leur potentiel de conversion" },
      "Hygiène CRM (Salesforce/HubSpot)",
      "Automatisation de Pipeline",
      "Reporting & KPIs",
    ],
  },
  {
    category: "Management & Soft Skills",
    items: [
      "Management de transition",
      "Recrutement de Talents",
      "Culture d'Entreprise",
      "Mentorat",
      { name: "Méthode OKR", subtitle: "Fixer des objectifs clairs et des résultats mesurables" },
      { name: "GTD (Getting Things Done)", subtitle: "Organiser ses tâches pour libérer l'esprit" },
      { name: "Deep Work", subtitle: "Travailler en profondeur sans distraction" },
      "Communication Asynchrone",
    ],
  },
  {
    category: "Sport Business & Partenariats",
    items: [
      "Commercialisation de Sponsoring (B2B)",
      "Ingénierie du Mécénat (Fiscalité & Éthique)",
      "Prospection de Grands Comptes Sportifs",
      "Rédaction de Dossiers de Partenariat",
      "Gestion de Loges VIP",
      "Expérience Client Jour de Match (Matchday Experience)",
      "Upsell de Prestations de Services",
      "Networking B2B en Environnement Sportif",
      "Activation Partenaire (Dispositifs 360°)",
      "Suivi Opérationnel de Contrat",
      "Gestion de Portefeuille Partenaires (Fidélisation & Rétention)",
      "Gestion de l'image (Personal Branding) des athlètes",
      "Analyse du ROI Partenaire (Visibilité/Engagement/Data)",
      "Reporting d'Impact (Social & Business)",
      "Étude de Notoriété de Marque",
    ],
  },
  {
    category: "Analyse comportementale & Intelligence",
    items: [
      "Neuromarketing",
      "Analyse des Parcours d'Achat",
      "Biais de Décision",
      "Psychologie des Prix",
      {
        name: "Étude des Motivations Profondes (Jobs-to-be-Done)",
        subtitle: "Comprendre le vrai besoin derrière la demande du client",
      },
      "Analyse Comportementale (Profilage)",
      "Lecture des Micro-expressions",
      "Analyse de la Voix (Tonalité & Stress)",
      "Profilage DISC & IDMC Appliqué",
      "Détection des Signaux Faibles (Tendances émergentes)",
      "Analyse de Données Prédictives",
      "Social Listening",
      "Veille Concurrentielle de Niche",
      "Éthique & RGPD de la donnée comportementale",
    ],
  },
  {
    category: "Marketing (Inbound, Growth & Content)",
    items: [
      { name: "Lead Nurturing", subtitle: "Entretenir la relation avec un prospect pas encore prêt" },
      "SEO sémantique (Bottom of Funnel)",
      "Stratégie de Content Marketing",
      "Lead Magnets",
      {
        name: "Framework AARRR",
        subtitle: "Acquisition, Activation, Rétention, Revenu, Recommandation",
      },
      "A/B Testing",
      "Scraping (Phantombuster)",
      "Automatisation (Make/Zapier)",
      "Analyse de Churn",
      {
        name: "Frameworks AIDA/PAS",
        subtitle: "Formules de rédaction publicitaire pour capter l'attention et convertir",
      },
      "Storytelling de Marque",
      "Micro-copy de Conversion (CTA)",
      "Ghostwriting LinkedIn",
    ],
  },
  {
    category: "Produit & Design",
    items: [
      "Méthode Agile/Scrum",
      "Gestion de Roadmap (Linear)",
      "User Stories",
      "Analyse de Feedback (Hotjar)",
      "UI Design (Figma)",
      "Prototypage",
      "Design Systems",
      "UX Research",
    ],
  },
  {
    category: "Développement Technique",
    items: [
      "React.js",
      { name: "Next.js (App Router)", subtitle: "Framework web moderne pour sites et applications" },
      "Tailwind CSS",
      "TypeScript",
      "Framer Motion",
      { name: "Web Accessibility (a11y)", subtitle: "Rendre un site utilisable par tous, y compris en situation de handicap" },
      "Node.js",
      { name: "Python (FastAPI)", subtitle: "Langage et framework pour APIs et scripts backend" },
      "Serverless Functions",
      "Edge Computing",
      "Docker",
      "Kubernetes",
      "PostgreSQL",
      "Supabase",
      "Redis (Cache)",
      { name: "Pinecone/Chroma", subtitle: "Bases de données vectorielles pour recherche sémantique" },
    ],
  },
  {
    category: "Intelligence Artificielle",
    items: [
      { name: "Prompt Engineering avancé", subtitle: "Formuler des consignes efficaces pour l'IA" },
      "Intégration APIs OpenAI",
      "Intégration APIs Anthropic",
      {
        name: "RAG (Retrieval-Augmented Generation)",
        subtitle: "Enrichir l'IA avec vos propres documents et données",
      },
      { name: "LangChain", subtitle: "Relier modèles IA, outils et sources de données" },
      { name: "Vercel AI SDK", subtitle: "Intégrer l'IA dans une application web Next.js" },
      { name: "Fine-tuning de modèles", subtitle: "Adapter un modèle IA à votre contexte métier" },
      "Automatisation IA (n8n)",
    ],
  },
];

export const TOOL_LOGOS: Record<string, string> = {
  notion: "https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png",
  wordpress: "https://upload.wikimedia.org/wikipedia/commons/2/20/WordPress_logo.svg",
  cursor: "https://avatars.githubusercontent.com/u/157243072?s=200&v=4",
  zapier: "https://upload.wikimedia.org/wikipedia/commons/7/75/Zapier_logo.svg",
  n8n: "https://upload.wikimedia.org/wikipedia/commons/5/5a/N8n-logo-new.svg",
  webflow: "https://upload.wikimedia.org/wikipedia/commons/3/3b/Webflow_logo.svg",
  react: "https://upload.wikimedia.org/wikipedia/commons/a/a7/React-icon.svg",
  "react.js": "https://upload.wikimedia.org/wikipedia/commons/a/a7/React-icon.svg",
  "next.js": "https://upload.wikimedia.org/wikipedia/commons/8/8e/Nextjs-logo.svg",
  typescript: "https://upload.wikimedia.org/wikipedia/commons/f/f5/Typescript.svg",
  tailwind: "https://upload.wikimedia.org/wikipedia/commons/d/d5/Tailwind_CSS_Logo.svg",
  "tailwind css": "https://upload.wikimedia.org/wikipedia/commons/d/d5/Tailwind_CSS_Logo.svg",
  node: "https://upload.wikimedia.org/wikipedia/commons/d/d9/Node.js_logo.svg",
  "node.js": "https://upload.wikimedia.org/wikipedia/commons/d/d9/Node.js_logo.svg",
  python: "https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg",
  docker: "https://upload.wikimedia.org/wikipedia/commons/4/4e/Docker_%28container_engine%29_logo.svg",
  kubernetes: "https://upload.wikimedia.org/wikipedia/commons/3/39/Kubernetes_logo_without_workmark.svg",
  supabase: "https://upload.wikimedia.org/wikipedia/commons/5/5d/Supabase-logo-icon.svg",
  redis: "https://upload.wikimedia.org/wikipedia/en/6/6b/Redis_Logo.svg",
  make: "https://images.ctfassets.net/qqlj6g4ee76j/4U1Pa4v8PS2zYJ57fRER8L/2dc2d32a9303aa9867f869db09fdf8d5/logo-mark.svg",
  hubspot: "https://upload.wikimedia.org/wikipedia/commons/3/3f/HubSpot_Logo.svg",
  salesforce: "https://upload.wikimedia.org/wikipedia/commons/f/f9/Salesforce.com_logo.svg",
  linear: "https://avatars.githubusercontent.com/u/11546552?s=200&v=4",
  hotjar: "https://upload.wikimedia.org/wikipedia/commons/e/e8/Hotjar_logo.svg",
  figma: "https://upload.wikimedia.org/wikipedia/commons/3/33/Figma-logo.svg",
};

export const resolveToolLogo = (toolName: string) => TOOL_LOGOS[toolName.trim().toLowerCase()] ?? null;
