import { EDGE_SITE_BASE } from "@/lib/edge-site/constants";

const B = EDGE_SITE_BASE;

/** Routes marketing EDGE (préfixées /edge-lab en local, racine sur edgebs.fr si rewrite). */
export const EDGE_MARKETING_ROUTES = {
  home: B,
  decouvrir: `${B}#decouvrir-edge`,
  apprenants: `${B}/apprenants`,
  formations: `${B}/formations`,
  formationsBts: `${B}/formations/bts`,
  formationsBachelor: `${B}/formations/bachelor`,
  formationsMastere: `${B}/formations/mastere`,
  alternance: `${B}/alternance`,
  admissions: `${B}/admissions`,
  financement: `${B}/financement`,
  vieEtudiante: `${B}/vie-etudiante`,
  certifications: `${B}/certifications`,
  business: `${B}/business`,
  businessSolutions: `${B}/business/solutions`,
  businessFormations: `${B}/business/formations-entreprises`,
  businessAcademie: `${B}/business/academie-interne`,
  businessCompetences: `${B}/business/gestion-competences`,
  businessRecrutement: `${B}/business/recrutement`,
  businessCasClients: `${B}/business/cas-clients`,
  businessDemo: `${B}/business/demo`,
  online: `${B}/online`,
  onlineFormations: `${B}/online/formations`,
  onlineBootcamps: `${B}/online/bootcamps`,
  onlineCertifications: `${B}/online/certifications`,
  formateursExperts: `${B}/formateurs-experts`,
  expertSignup: "/signup/expert",
  expertDashboard: "/dashboard/expert",
  aPropos: `${B}/a-propos`,
  notreMission: `${B}/notre-mission`,
  ressources: `${B}/ressources`,
  blog: `${B}/blog`,
  guides: `${B}/guides`,
  webinaires: `${B}/webinaires`,
  tarifs: `${B}/tarifs`,
  contact: `${B}/contact`,
  login: "/login",
  parcours: `${B}/parcours`,
  entreprises: `${B}/entreprises`,
} as const;
