import type { MarketingPageKey } from "@/lib/edge-site/marketing-content";

/** Chemin sous /edge-lab → clé contenu marketing. */
export const MARKETING_PAGE_REGISTRY: { path: string; key: MarketingPageKey }[] = [
  { path: "apprenants", key: "apprenants" },
  { path: "formations", key: "formations" },
  { path: "formations/bts", key: "formationsBts" },
  { path: "formations/bachelor", key: "formationsBachelor" },
  { path: "formations/mastere", key: "formationsMastere" },
  { path: "alternance", key: "alternance" },
  { path: "admissions", key: "admissions" },
  { path: "financement", key: "financement" },
  { path: "vie-etudiante", key: "vieEtudiante" },
  { path: "certifications", key: "certifications" },
  { path: "business", key: "business" },
  { path: "business/solutions", key: "businessSolutions" },
  { path: "business/formations-entreprises", key: "businessFormations" },
  { path: "business/academie-interne", key: "businessAcademie" },
  { path: "business/gestion-competences", key: "businessCompetences" },
  { path: "business/recrutement", key: "businessRecrutement" },
  { path: "business/cas-clients", key: "businessCasClients" },
  { path: "business/demo", key: "businessDemo" },
  { path: "online", key: "online" },
  { path: "online/formations", key: "onlineFormations" },
  { path: "online/bootcamps", key: "onlineBootcamps" },
  { path: "online/certifications", key: "onlineCertifications" },
  { path: "formateurs-experts", key: "formateursExperts" },
  { path: "a-propos", key: "aPropos" },
  { path: "notre-mission", key: "notreMission" },
  { path: "ressources", key: "ressources" },
  { path: "blog", key: "blog" },
  { path: "guides", key: "guides" },
  { path: "webinaires", key: "webinaires" },
  { path: "contact", key: "contact" },
  { path: "tarifs", key: "tarifs" },
];
