export type BusinessTrainingItem = {
  id: string;
  category: string;
  title: string;
  subtitle: string;
  duration: string;
  level: string;
  format: string;
  expert: string;
  companiesCount: number;
  participants: string;
  startingPrice: string;
};

export const BUSINESS_TRAINING_CATEGORIES = [
  "Tous",
  "Management",
  "IA",
  "Communication",
  "Soft Skills",
  "RH",
  "Commerce",
  "Projet",
  "Pédagogie",
  "Leadership",
] as const;

export const BUSINESS_TRAINING_ITEMS: BusinessTrainingItem[] = [
  {
    id: "account-management-fidelisation",
    category: "Commerce",
    title: "Account management et fidélisation",
    subtitle: "Développer les comptes",
    duration: "2,5 jours",
    level: "Expert",
    format: "Présentiel · Distanciel · Blended",
    expert: "Sales Performance Expert",
    companiesCount: 129,
    participants: "Jusqu'à 12 participants",
    startingPrice: "2 490 €",
  },
  {
    id: "adapter-communication-profil",
    category: "Communication",
    title: "Adapter sa communication selon le profil",
    subtitle: "Personnaliser le message",
    duration: "2 jours",
    level: "Confirmé",
    format: "Présentiel · Distanciel · Blended",
    expert: "Behavioral Intelligence Expert",
    companiesCount: 41,
    participants: "Jusqu'à 12 participants",
    startingPrice: "1 890 €",
  },
  {
    id: "analyse-comportementale-vente",
    category: "Commerce",
    title: "Analyse comportementale appliquée à la vente",
    subtitle: "Adapter le discours commercial",
    duration: "2 jours",
    level: "Confirmé",
    format: "Présentiel · Distanciel · Blended",
    expert: "Behavioral Intelligence Expert",
    companiesCount: 40,
    participants: "Jusqu'à 12 participants",
    startingPrice: "1 890 €",
  },
  {
    id: "analyse-comportementale-management",
    category: "Management",
    title: "Analyse comportementale appliquée au management",
    subtitle: "Manager les différences",
    duration: "2,5 jours",
    level: "Expert",
    format: "Présentiel · Distanciel · Blended",
    expert: "Behavioral Intelligence Expert",
    companiesCount: 39,
    participants: "Jusqu'à 12 participants",
    startingPrice: "2 490 €",
  },
  {
    id: "animer-avec-impact",
    category: "Pédagogie",
    title: "Animer avec impact",
    subtitle: "Engager les apprenants",
    duration: "1,5 jour",
    level: "Praticien",
    format: "Présentiel · Distanciel · Blended",
    expert: "Trainer Expert",
    companiesCount: 76,
    participants: "Jusqu'à 12 participants",
    startingPrice: "1 290 €",
  },
  {
    id: "entretien-comportemental",
    category: "RH",
    title: "Animer un entretien comportemental",
    subtitle: "Structurer l'entretien",
    duration: "3 jours",
    level: "Stratège",
    format: "Présentiel · Distanciel · Blended",
    expert: "Behavioral Intelligence Expert",
    companiesCount: 37,
    participants: "Jusqu'à 12 participants",
    startingPrice: "3 200 €",
  },
  {
    id: "equipe-projet",
    category: "Projet",
    title: "Animer une équipe projet",
    subtitle: "Coordonner les contributeurs",
    duration: "2 jours",
    level: "Confirmé",
    format: "Présentiel · Distanciel · Blended",
    expert: "Project Expert",
    companiesCount: 59,
    participants: "Jusqu'à 12 participants",
    startingPrice: "1 890 €",
  },
  {
    id: "assertivite",
    category: "Communication",
    title: "Assertivité : s'affirmer sans s'imposer",
    subtitle: "S'affirmer avec respect",
    duration: "1,5 jour",
    level: "Praticien",
    format: "Présentiel · Distanciel · Blended",
    expert: "Négociation Expert",
    companiesCount: 125,
    participants: "Jusqu'à 12 participants",
    startingPrice: "1 290 €",
  },
  {
    id: "ia-commerciale-processus",
    category: "IA",
    title: "Automatisation et IA Commerciale : Optimisez vos Processus",
    subtitle: "Transformer vos processus commerciaux",
    duration: "1,5 jour",
    level: "Praticien",
    format: "Présentiel · Distanciel · Blended",
    expert: "Expert en Automatisation et IA Commerciale",
    companiesCount: 142,
    participants: "Jusqu'à 12 participants",
    startingPrice: "1 290 €",
  },
  {
    id: "automatiser-taches-ia",
    category: "IA",
    title: "Automatiser des tâches avec l'IA",
    subtitle: "Identifier les tâches automatisables",
    duration: "2 jours",
    level: "Confirmé",
    format: "Présentiel · Distanciel · Blended",
    expert: "IA Strategy Expert",
    companiesCount: 102,
    participants: "Jusqu'à 12 participants",
    startingPrice: "1 890 €",
  },
  {
    id: "leader-mythes-realites",
    category: "Leadership",
    title: "C'est quoi un leader ? Mythes et réalités",
    subtitle: "Définir le leadership",
    duration: "1 jour",
    level: "Fondamentaux",
    format: "Présentiel · Distanciel · Blended",
    expert: "Leader Expert",
    companiesCount: 94,
    participants: "Jusqu'à 12 participants",
    startingPrice: "890 €",
  },
  {
    id: "collaboration-intelligence-collective",
    category: "Soft Skills",
    title: "Collaboration et intelligence collective",
    subtitle: "Co-construire en équipe",
    duration: "2,5 jours",
    level: "Expert",
    format: "Présentiel · Distanciel · Blended",
    expert: "Soft Skills Expert",
    companiesCount: 43,
    participants: "Jusqu'à 12 participants",
    startingPrice: "2 490 €",
  },
  {
    id: "communication-strategique",
    category: "Communication",
    title: "Communication stratégique et influence organisationnelle",
    subtitle: "Influencer les décisions",
    duration: "3 jours",
    level: "Stratège",
    format: "Présentiel · Blended",
    expert: "Stratège Communication Expert",
    companiesCount: 105,
    participants: "Jusqu'à 12 participants",
    startingPrice: "3 200 €",
  },
  {
    id: "comprendre-ia",
    category: "IA",
    title: "Comprendre l'IA : ce que c'est, ce que ce n'est pas",
    subtitle: "Démystifier l'IA",
    duration: "1 jour",
    level: "Fondamentaux",
    format: "Présentiel · Distanciel · Blended",
    expert: "IA Strategy Expert",
    companiesCount: 98,
    participants: "Jusqu'à 12 participants",
    startingPrice: "890 €",
  },
  {
    id: "comprendre-ses-emotions",
    category: "Soft Skills",
    title: "Comprendre ses émotions",
    subtitle: "Nommer ses émotions",
    duration: "1 jour",
    level: "Fondamentaux",
    format: "Présentiel · Distanciel · Blended",
    expert: "Soft Skills Expert",
    companiesCount: 48,
    participants: "Jusqu'à 12 participants",
    startingPrice: "890 €",
  },
  {
    id: "parcours-blended",
    category: "Pédagogie",
    title: "Concevoir un parcours blended",
    subtitle: "Mixer les formats",
    duration: "1,5 jour",
    level: "Praticien",
    format: "Présentiel · Distanciel · Blended",
    expert: "Trainer Expert",
    companiesCount: 77,
    participants: "Jusqu'à 12 participants",
    startingPrice: "1 290 €",
  },
  {
    id: "conduire-changement",
    category: "Management",
    title: "Conduire le changement",
    subtitle: "Anticiper les résistances",
    duration: "2,5 jours",
    level: "Expert",
    format: "Présentiel · Distanciel · Blended",
    expert: "Leader Expert",
    companiesCount: 99,
    participants: "Jusqu'à 12 participants",
    startingPrice: "2 490 €",
  },
  {
    id: "entretien-recrutement",
    category: "RH",
    title: "Conduire un entretien de recrutement",
    subtitle: "Structurer l'entretien",
    duration: "1,5 jour",
    level: "Praticien",
    format: "Présentiel · Distanciel · Blended",
    expert: "RH & Talents Expert",
    companiesCount: 66,
    participants: "Jusqu'à 12 participants",
    startingPrice: "1 290 €",
  },
  {
    id: "workflow-no-code",
    category: "IA",
    title: "Construire un workflow automatisé no-code",
    subtitle: "Modéliser un workflow",
    duration: "2 jours",
    level: "Confirmé",
    format: "Présentiel · Distanciel · Blended",
    expert: "Commercial Automation Expert",
    companiesCount: 54,
    participants: "Jusqu'à 12 participants",
    startingPrice: "1 890 €",
  },
  {
    id: "strategie-transformation-ia",
    category: "IA",
    title: "Construire une stratégie de transformation IA",
    subtitle: "Prioriser les chantiers",
    duration: "3 jours",
    level: "Stratège",
    format: "Présentiel · Blended",
    expert: "IA Strategy Expert",
    companiesCount: 105,
    participants: "Jusqu'à 12 participants",
    startingPrice: "3 200 €",
  },
  {
    id: "fondamentaux-recrutement",
    category: "RH",
    title: "Fondamentaux du recrutement efficace",
    subtitle: "Définir un besoin",
    duration: "1 jour",
    level: "Fondamentaux",
    format: "Présentiel · Distanciel · Blended",
    expert: "RH & Talents Expert",
    companiesCount: 64,
    participants: "Jusqu'à 12 participants",
    startingPrice: "890 €",
  },
  {
    id: "gpec-mobilite",
    category: "RH",
    title: "GPEC et mobilité interne",
    subtitle: "Cartographier les compétences",
    duration: "2,5 jours",
    level: "Expert",
    format: "Présentiel · Distanciel · Blended",
    expert: "RH & Talents Expert",
    companiesCount: 69,
    participants: "Jusqu'à 12 participants",
    startingPrice: "2 490 €",
  },
  {
    id: "ia-generative-equipe",
    category: "IA",
    title: "IA générative en équipe",
    subtitle: "Collaborer avec l'IA",
    duration: "2 jours",
    level: "Confirmé",
    format: "Présentiel · Distanciel · Blended",
    expert: "IA Strategy Expert",
    companiesCount: 101,
    participants: "Jusqu'à 12 participants",
    startingPrice: "1 890 €",
  },
  {
    id: "ingenierie-pedagogique",
    category: "Pédagogie",
    title: "Ingénierie pédagogique : les fondamentaux",
    subtitle: "Analyser un besoin",
    duration: "1 jour",
    level: "Fondamentaux",
    format: "Présentiel · Distanciel · Blended",
    expert: "Trainer Expert",
    companiesCount: 78,
    participants: "Jusqu'à 12 participants",
    startingPrice: "890 €",
  },
  {
    id: "manager-profils-differents",
    category: "Management",
    title: "Manager des profils différents",
    subtitle: "Adapter son management",
    duration: "2 jours",
    level: "Confirmé",
    format: "Présentiel · Distanciel · Blended",
    expert: "Leader Expert",
    companiesCount: 97,
    participants: "Jusqu'à 12 participants",
    startingPrice: "1 890 €",
  },
  {
    id: "prise-parole-public",
    category: "Communication",
    title: "Prise de parole en public : structure et impact",
    subtitle: "Structurer un pitch",
    duration: "2 jours",
    level: "Confirmé",
    format: "Présentiel · Distanciel · Blended",
    expert: "Stratège Communication Expert",
    companiesCount: 102,
    participants: "Jusqu'à 12 participants",
    startingPrice: "1 890 €",
  },
  {
    id: "prospection-multicanale",
    category: "Commerce",
    title: "Prospection multicanale efficace",
    subtitle: "Combiner les canaux",
    duration: "1,5 jour",
    level: "Praticien",
    format: "Présentiel · Distanciel · Blended",
    expert: "Sales Performance Expert",
    companiesCount: 132,
    participants: "Jusqu'à 12 participants",
    startingPrice: "1 290 €",
  },
  {
    id: "sourcing-attractivite",
    category: "RH",
    title: "Sourcing et attractivité des talents",
    subtitle: "Diversifier les canaux",
    duration: "1,5 jour",
    level: "Praticien",
    format: "Présentiel · Distanciel · Blended",
    expert: "RH & Talents Expert",
    companiesCount: 65,
    participants: "Jusqu'à 12 participants",
    startingPrice: "1 290 €",
  },
  {
    id: "storytelling-professionnel",
    category: "Communication",
    title: "Storytelling professionnel",
    subtitle: "Raconter une histoire métier",
    duration: "2,5 jours",
    level: "Expert",
    format: "Présentiel · Distanciel · Blended",
    expert: "Stratège Communication Expert",
    companiesCount: 103,
    participants: "Jusqu'à 12 participants",
    startingPrice: "2 490 €",
  },
  {
    id: "travailler-ia-collaboratif",
    category: "IA",
    title: "Travailler avec l'IA en mode collaboratif",
    subtitle: "Co-construire avec l'IA",
    duration: "2,5 jours",
    level: "Expert",
    format: "Présentiel · Distanciel · Blended",
    expert: "IA Strategy Expert",
    companiesCount: 104,
    participants: "Jusqu'à 12 participants",
    startingPrice: "2 490 €",
  },
  {
    id: "ia-prospection-commerciale",
    category: "IA",
    title: "Utiliser l'IA pour la prospection commerciale",
    subtitle: "Qualifier les comptes",
    duration: "1,5 jour",
    level: "Praticien",
    format: "Présentiel · Distanciel · Blended",
    expert: "Commercial Automation Expert",
    companiesCount: 56,
    participants: "Jusqu'à 12 participants",
    startingPrice: "1 290 €",
  },
];
